digit = '0' .. '9'
capitalLetter = 'A' .. 'Z'
lowercaseLetter = 'a' .. 'z'
letter =  capitalLetter | lowercaseLetter | '\x80' .. '\xff'
letterSequence = letter { letter }
mark = '.' | ',' | '!' | '?' | ':' | ';' | '_' | '-' | '+' | '='

sign = '+' | '-'
unsignedNumber = digit { digit }
signedNumber = [ sign ] unsignedNumber
number = signedNumber [ '.' [ unsignedNumber ] ] [ ( 'e' | 'E' )  unsignedNumber ]

charLiteral = ''' letter | digit '''
stringLiteral = '"' letter { letter | ' ' } '"'
identifier = letter { letter | unsignedNumber }
